apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: juanbevilacqua/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: "."
    - image: juanbevilacqua/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: "."
    - image: juanbevilacqua/ticketing-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: "."
    - image: juanbevilacqua/ticketing-orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: "."
    - image: juanbevilacqua/ticketing-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: "."
    - image: juanbevilacqua/ticketing-payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: "."
manifests:
  rawYaml:
    - infra/k8s/*
    - infra/k8s-dev/*
